config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"

  resources :stations, only: [:index, :show]

  resources :trips, only: [:index, :show]

  resources :conditions, only: [:index, :show]

  resources :users, except: [:index, :destroy, :show]

  get "/stations-dashboard", :to => "stations_dashboard#index"

  get "/trips-dashboard", :to => "trips_dashboard#index"

  get "/weather-dashboard", :to => "weather_dashboard#index"

  get "/dashboard", :to => "users#show"

  get "/login", to: "sessions#new"

  post "/login", to: "sessions#create"

  delete "/logout", to: "sessions#destroy"

  namespace :admin do
    get "/dashboard", :to => "dashboard#show"
    resources :trips, except: [:index, :show]
    resources :stations, except: [:index, :show]
    resources :conditions, except: [:index, :show]
    get "bike-shop", :to => "bike_shop#index"
    get "bike-shop/new", :to => "accessories#new"
    resources :accessories, only: [:edit, :update, :create, :show]
    resources :orders, only: [:update, :edit, :index, :show]
  end

  get "/bike-shop", :to => "bike_shop/accessories#index"

  namespace :bike_shop do
    resources :accessories, except: [:index]
  end

  resources :cart, only: [:create, :index, :destroy]

  resources :orders, only: [:create, :new, :show, :update]
end

app/models/station.rb
class Station < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  validates_presence_of :name, :dock_count, :city, :installation_date

  has_many :start_trips, class_name: "Trip", foreign_key: "start_station_id"
  has_many :end_trips, class_name: "Trip", foreign_key: "end_station_id"

  def self.average_bike_count
    average(:dock_count)
  end

  def self.highest_bike_count
    maximum(:dock_count)
  end

  def self.station_with_highest_bike_count
    where("dock_count >= ?", maximum(:dock_count))
  end

  def self.fewest_bike_count
    minimum(:dock_count)
  end

  def self.station_with_lowest_bike_count
    where("dock_count <= ?", minimum(:dock_count))
  end

  def self.newest_station
    where("installation_date >= ?", maximum(:installation_date))
  end

  def self.oldest_station
    where("installation_date <= ?", minimum(:installation_date))
  end

  def total_rides_started
    start_trips.count
  end

  def total_rides_ended
    end_trips.count
  end

  def most_frequent_end_station
    start_trips.select("trips.*, count(trips.id) AS trip_count")
    .group(:start_station_id, :id)
    .order('trip_count DESC')
    .first
    .end_station
  end

  def most_frequent_start_station
    end_trips.select("trips.*, count(trips.id) AS trip_count")
    .group(:end_station_id, :id)
    .order("trip_count DESC")
    .first
    .start_station
  end

  def highest_originations_by_date
    start_trips.group(:start_date)
    .order("count(*) DESC")
    .count
    .first
  end

  def most_common_zip
    start_trips.group(:zip_code)
    .order("count(*) DESC")
    .count
    .first
  end

  def most_common_bike
    start_trips.group(:bike_id)
    .order("count(*) DESC")
    .count
    .first
  end
end

app/controllers/admin/stations_controller.rb
class Admin::StationsController < Admin::BaseController
  before_action :find_station, only: [:edit, :update, :destroy]

  def new
    @station = Station.new
  end

  def edit
  end

  def create
    @station = Station.new(station_params)
    if @station.save
      flash[:notice] = "Station created"
      redirect_to station_path(@station)
    else
      flash[:notice] = "Station not created. Try again."
      redirect_to new_admin_station_path
    end
  end

  def update
    if @station.update(station_params)
      flash[:notice] = "Station updated"
      redirect_to station_path(@station)
    else
      flash[:notice] = "Station not updated. Try again."
      redirect_to edit_admin_station_path(@station)
    end
  end

  def destroy
    @station.destroy
    flash[:notice] = "Station deleted =("
    redirect_to stations_path
  end

  private

    def station_params
      params.require(:station).permit(:name, :dock_count, :city, :installation_date)
    end

    def find_station
      @station = Station.friendly.find(params[:id])
    end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController

  def index
    @stations = Station.all
  end

  def show
    @station = Station.friendly.find(params[:id])
  end
end

app/views/stations/_analytics.html.erb
<section class="stations-dashboard-analytics">
  <section class="stations-dashboard-value">
    Installation Date: <%= @station.installation_date %>
  </section>
  <section class="stations-dashboard-value">
    Total Rides Started Here: <%= @station.total_rides_started %>
  </section>
  <section class="stations-dashboard-value">
    Total Rides Ended Here: <%= @station.total_rides_ended %>
  </section>
  <section class="stations-dashboard-value">
    Most Frequent Destination: <%= link_to @station.most_frequent_end_station.name, station_path(@station.most_frequent_end_station) %>
  </section>
  <section class="stations-dashboard-value">
    Most Frequent Origination: <%= link_to @station.most_frequent_start_station.name, station_path(@station.most_frequent_start_station) %>
  </section>
  <section class="stations-dashboard-value">
    Date with Highest Number of Trips: <%= @station.highest_originations_by_date[0].strftime("%F") %>
  </section>
  <section class="stations-dashboard-value">
    Most Common User Zip Code: <%= @station.most_common_zip[0] %>
  </section>
  <section class="stations-dashboard-value">
    Most Popular Bike: <%= @station.most_common_bike[0] %>
  </section>
</section>

app/views/stations/index.html.erb
<br>
<section class="button">
  <h3><%= link_to "Create New Station", new_admin_station_path if current_admin? %></h3>
</section>
<section class="trips-dashboard-analytics">
    <% @stations.each do |station| %>
      <section class="trips-dashboard-value">
        <h3><%= link_to station.name, station_path(station) %></h3>
        Dock Count: <%= station.dock_count %><br>
        City: <%= station.city %><br>
        Installation Date: <%= station.installation_date %>
        <%= link_to "Edit", edit_admin_station_path(station) if current_admin? %>
        <%= link_to "Delete", admin_station_path(station), method: "delete" if current_admin? %>
      </section>
    <% end %>
</section>

app/views/stations/show.html.erb
<section class="stations-dashboard-analytics">
  <section class="stations-dashboard-value">
    <h2>
      Name: <%= @station.name %><br>
      Dock Count: <%= @station.dock_count %><br>
      City: <%= @station.city %><br>
      Installation Date: <%= @station.installation_date %><br>
      <%= render partial: "analytics" if current_user && has_trips? %><br>
      <%= link_to "Edit", edit_admin_station_path(@station) if current_admin? %><br>
      <%= link_to "Delete", admin_station_path(@station), method: "delete" if current_admin? %><br>
    </h2>
  </section>
</section>