config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"

  resources :stations, only: [:index, :show]

  resources :trips, only: [:index, :show]

  resources :conditions, only: [:index, :show]

  resources :users, except: [:index, :destroy, :show]

  get "/stations-dashboard", :to => "stations_dashboard#index"

  get "/trips-dashboard", :to => "trips_dashboard#index"

  get "/weather-dashboard", :to => "weather_dashboard#index"

  get "/dashboard", :to => "users#show"

  get "/login", to: "sessions#new"

  post "/login", to: "sessions#create"

  delete "/logout", to: "sessions#destroy"

  namespace :admin do
    get "/dashboard", :to => "dashboard#show"
    resources :trips, except: [:index, :show]
    resources :stations, except: [:index, :show]
    resources :conditions, except: [:index, :show]
    get "bike-shop", :to => "bike_shop#index"
    get "bike-shop/new", :to => "accessories#new"
    resources :accessories, only: [:edit, :update, :create, :show]
    resources :orders, only: [:update, :edit, :index, :show]
  end

  get "/bike-shop", :to => "bike_shop/accessories#index"

  namespace :bike_shop do
    resources :accessories, except: [:index]
  end

  resources :cart, only: [:create, :index, :destroy]

  resources :orders, only: [:create, :new, :show, :update]
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  def show
    @orders = Order.all
    @status_orders = find_by_status
  end

  private

    def find_by_status
      case params[:status]
      when "Ordered"
        Order.ordered
      when "Paid"
        Order.paid
      when "Cancelled"
        Order.cancelled
      when "Completed"
        Order.completed
      else
        []
      end
    end
end

app/views/admin/dashboard/_status.html.erb
<h1>Orders with the status of <%= @status_orders.first.status %></h1>
<% @status_orders.each do |order| %>
  <h1><%= order.status %> Order: #<%= order.id %></h1>
  <p><%= link_to "Cancel Order", order_path(order, status: "Cancelled"), method: "patch" if !@status_orders.paid.empty? || !@status_orders.ordered.empty? %></p>
  <p><%= link_to "Mark as Paid", order_path(order, status: "Paid"), method: "patch" if !@status_orders.ordered.empty? %></p>
  <p><%= link_to "Mark as Completed", order_path(order, status: "Completed"), method: "patch" if !@status_orders.paid.empty? %></p>
<% end %>

app/views/admin/dashboard/show.html.erb
<section class="welcome-about">
  <h1>Logged in as <%= current_user.name %></h1>
  <p>Current Email: <%= current_user.email %></p>
  See something that doesn't look right? <%= link_to "Edit Profile", edit_user_path(current_user) %>
  <%= link_to "View Accessories", admin_bike_shop_path %>
  <%= link_to "Station Dashboard", stations_dashboard_path %>
  <%= link_to "Trips Dashboard", trips_dashboard_path %>
  <%= link_to "Weather Conditions Dashboard", weather_dashboard_path %>

  <% @orders.each do |order| %>
    Order #<%= link_to order.id, admin_order_path(order) %>
  <% end %>

  <%= link_to "Ordered", admin_dashboard_path(:status => "Ordered") %>: <%= @orders.ordered.count %>
  <%= link_to "Cancelled", admin_dashboard_path(:status => "Cancelled") %>: <%= @orders.cancelled.count %>
  <%= link_to "Paid", admin_dashboard_path(:status => "Paid") %>: <%= @orders.paid.count %>
  <%= link_to "Completed", admin_dashboard_path(:status => "Completed") %>: <%= @orders.completed.count %>

  <%= render partial: "status" if !@status_orders.empty? %>
</section>