config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"

  resources :stations, only: [:index, :show]

  resources :trips, only: [:index, :show]

  resources :conditions, only: [:index, :show]

  resources :users, except: [:index, :destroy, :show]

  get "/stations-dashboard", :to => "stations_dashboard#index"

  get "/trips-dashboard", :to => "trips_dashboard#index"

  get "/weather-dashboard", :to => "weather_dashboard#index"

  get "/dashboard", :to => "users#show"

  get "/login", to: "sessions#new"

  post "/login", to: "sessions#create"

  delete "/logout", to: "sessions#destroy"

  namespace :admin do
    get "/dashboard", :to => "dashboard#show"
    resources :trips, except: [:index, :show]
    resources :stations, except: [:index, :show]
    resources :conditions, except: [:index, :show]
    get "bike-shop", :to => "bike_shop#index"
    get "bike-shop/new", :to => "accessories#new"
    resources :accessories, only: [:edit, :update, :create, :show]
    resources :orders, only: [:update, :edit, :index, :show]
  end

  get "/bike-shop", :to => "bike_shop/accessories#index"

  namespace :bike_shop do
    resources :accessories, except: [:index]
  end

  resources :cart, only: [:create, :index, :destroy]

  resources :orders, only: [:create, :new, :show, :update]
end

app/models/order.rb
class Order < ApplicationRecord
  validates_presence_of :purchaser_name, :purchaser_address, :status, :user_id
  belongs_to :user
  has_many :ordered_accessories
  has_many :accessories, through: :ordered_accessories

  def total_cost
    ordered_accessories.sum do |ordered_accessory|
      Accessory.find(ordered_accessory.accessory_id).price * ordered_accessory.quantity
    end
  end

  def self.completed
    where(status: "Completed")
  end

  def self.ordered
    where(status: "Ordered")
  end

  def self.cancelled
    where(status: "Cancelled")
  end

  def self.paid
    where(status: "Paid")
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < Admin::BaseController

  def index
    @orders = Order.all 
  end

  def show
    @order = Order.find(params[:id])
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :check_users_orders, only: [:show]

  def show
  end

  def new
    if current_user
      @order = Order.new
    else
      flash[:notice] = "Please login first"
      redirect_to login_path
    end
  end

  def create
    if current_user
      @order = Order.new(order_params)
      @order.user_id = params[:user_id].keys[0]
      @order.status = params[:status].keys[0]
      if @order.save
        session[:cart].each do |order|
          OrderedAccessory.create!(accessory_id: order[0], order_id: @order.id, quantity: order[1])
        end
        flash[:notice] = "You have successfully submitted your order!"
        session[:cart] = nil
        redirect_to dashboard_path(current_user)
      else

      end
    else
      redirect_to login_path
    end
  end

  def update
    @order = Order.find(params[:id])
    @order.update(status: params[:status])
    flash[:notice] = "#{@order.id} has been #{params[:status]}"
    redirect_to admin_dashboard_path(params[:status])
  end

  private

    def order_params
      params.require(:order).permit(:purchaser_name, :purchaser_address)
    end

    def check_users_orders
      if current_user.id == Order.find(params[:id]).user_id
        @order = Order.find(params[:id])
      else
        render file: "/public/404"
      end
    end

end

app/views/admin/orders/index.html.erb
<section class="welcome-about">
  <% @orders.each do |order| %>
    <%= order.purchaser_name %>
    <%= order.purchaser_address %>
    <%= order.status %>
    <%= order.user_id %>
    <%= order.created_at %>
  <% end %>
</section>

app/views/admin/orders/show.html.erb
<section class="welcome-about">
  <h1>Name: <%= @order.purchaser_name %></h1>
  <p>Address: <%= @order.purchaser_address %></p>
  <p>Order Updated At: <%= @order.updated_at %></p>
  <% @order.accessories.each do |accessory| %>
    <h1><%= link_to accessory.name, admin_accessory_path(accessory) %></h1>
    <p>Quantity: <%= accessory.total_quantity %></p>
    <p>Line Item Subtotal: <%= number_to_currency(accessory.price * accessory.total_quantity) %></p>
  <% end %>
  <p>Total Cost: <%= number_to_currency(@order.total_cost) %></p>
  <p>Status: <%= @order.status %></p>
</section>