config/routes.rb
Rails.application.routes.draw do

  root "welcome#index"

  resources :stations, only: [:index, :show]

  resources :trips, only: [:index, :show]

  resources :conditions, only: [:index, :show]

  resources :users, except: [:index, :destroy, :show]

  get "/stations-dashboard", :to => "stations_dashboard#index"

  get "/trips-dashboard", :to => "trips_dashboard#index"

  get "/weather-dashboard", :to => "weather_dashboard#index"

  get "/dashboard", :to => "users#show"

  get "/login", to: "sessions#new"

  post "/login", to: "sessions#create"

  delete "/logout", to: "sessions#destroy"

  namespace :admin do
    get "/dashboard", :to => "dashboard#show"
    resources :trips, except: [:index, :show]
    resources :stations, except: [:index, :show]
    resources :conditions, except: [:index, :show]
    get "bike-shop", :to => "bike_shop#index"
    get "bike-shop/new", :to => "accessories#new"
    resources :accessories, only: [:edit, :update, :create, :show]
    resources :orders, only: [:update, :edit, :index, :show]
  end

  get "/bike-shop", :to => "bike_shop/accessories#index"

  namespace :bike_shop do
    resources :accessories, except: [:index]
  end

  resources :cart, only: [:create, :index, :destroy]

  resources :orders, only: [:create, :new, :show, :update]
end

app/models/accessory.rb
class Accessory < ApplicationRecord
  validates_presence_of :name, :description, :price, :role

  has_attached_file :image,
  :styles => { :medium => "200x200>", :thumb => "100x100>" },
  :default_url => "https://i.pinimg.com/736x/53/10/e0/5310e0e6382af61565718f90e8502233--baby-nerd-hipster-babies.jpg"
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

  has_many :ordered_accessories
  has_many :orders, through: :ordered_accessories

  def total_quantity
    ordered_accessories.sum do |ordered_accessory|
      ordered_accessory.quantity
    end
  end
end

app/controllers/admin/accessories_controller.rb
class Admin::AccessoriesController < Admin::BaseController
  before_action :find_accessory, only: [:edit, :update, :show]

  def edit
  end

  def new
    @accessory = Accessory.new
  end

  def show
  end

  def create
    @accessory = Accessory.new(accessory_params)
    @accessory.update_attribute(:image, params[:accessory][:image])
    if @accessory.save
      flash[:notice] = "Accessory created"
      redirect_to admin_accessory_path(@accessory)
    else
      flash[:notice] = "Accessory not created. Try again."
      render :new
    end
  end

  def update
    if @accessory.update(accessory_params)
      @accessory.update_attribute(:image, params[:accessory][:image])
      flash[:notice] = "Accessory updated"
      redirect_to admin_bike_shop_path
    else
      flash[:notice] = "Accessory not updated. Try again."
      render :edit
    end
  end

  private

    def find_accessory
      @accessory = Accessory.find(params[:id])
    end

    def accessory_params
      params.require(:accessory).permit(:name, :description, :price, :role)
    end
end

app/controllers/admin/bike_shop_controller.rb
class Admin::BikeShopController < Admin::BaseController

  def index
    @active_accessories = Accessory.where(role: 0)
    @inactive_accessories = Accessory.where(role: 1)
  end

end

app/controllers/bike_shop/accessories_controller.rb
class BikeShop::AccessoriesController < BikeShop::BaseController

  def index
    @accessories = Accessory.all
  end

  def show
    @accessory = Accessory.find(params[:id])
  end

end

app/controllers/bike_shop/base_controller.rb
class BikeShop::BaseController < ApplicationController

end

app/views/bike_shop/accessories/_active.html.erb
<p><%= button_to "Add to Cart", cart_index_path(accessory: @accessory.id) %></p>

app/views/bike_shop/accessories/_inactive.html.erb
<p>Accessory Retired. <%= link_to "Find a similar item", "https://www.amazon.com/s/ref=nb_sb_ss_c_1_9?url=search-alias%3Daps&field-keywords=bike+accessories+#{@accessory.name}&sprefix=Bike+acce%2Caps%2C163&crid=3D4EI6G7KRBPB" %></p>

app/views/bike_shop/accessories/index.html.erb
<% @accessories.each do |accessory| %>
<div class="accessory-card">
  <%= image_tag accessory.image.url %>
  <center><p><%= link_to accessory.name, bike_shop_accessory_path(accessory) %></p>
  <%= accessory.description %>
  <p><%= number_to_currency(accessory.price) %></p>
    <%= button_to "Add to Cart", cart_index_path(accessory: accessory.id) %></center>
  </div>
<% end %>

app/views/bike_shop/accessories/show.html.erb
<h1><%= @accessory.name %></h1>
<p><%= @accessory.description %></p>
<p><%= number_to_currency(@accessory.price) %></p>
<%= render partial: "active" if @accessory.role == 0 %>
<%= render partial: "inactive" if @accessory.role == 1 %>